version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: binance_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./_docker/nginx/ssl:/etc/nginx/ssl
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        container_name: binance_app
        volumes:
            - ./:/var/www/html/
        depends_on:
            - db

    db:
        image: mysql:8.1
        container_name: binance_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: binance
            MYSQL_ROOT_PASSWORD: root
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
